### ISSUE TITLE
Modifier names are not display during damage rolls

### ISSUE THREAD

**Issue by rokiyo** [wildj79/foundryvtt-starfinder#428]
I have added the following modifiers to an active feat (triggered by a move action):
![image](https://user-images.githubusercontent.com/4364040/127766466-438c4144-b318-4df4-ba57-68d94d961542.png)

While the feat is activated, the following can be seen in the attack and damage rolls for the affected items:
![image](https://user-images.githubusercontent.com/4364040/127766449-21198ba2-f35a-4bd0-9147-1931f55fce77.png)

Note that the modifier's name is displayed in the attack roll breakdown, but not in the damage roll breakdown.

**Comment by wildj79** [comment]
This is fixed in my current feature branch. It should be released in the near future (one to two weeks from this comment).

**Comment by TimToxopeus** [comment]
Noticed it wasn't actually fixed, so fixed it myself just now. I'm not sure if that was simply a missed part of your branch or not.
Will be part of the next release.
